# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
platform :ios, '7.0'
pod 'pop', '~> 1.0'
#target 'L04动画引擎中POP CALayer与CALayer的联系与区别' do

#end

