# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'L04POP动画引擎中Layer与CALayer的联系与区别' do
	platform :ios, '8.0'
	pod 'pop', '~> 1.0'
end

